# Generated by Django 5.2.14 on 2026-05-26 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Shinny Tienda', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='store/')),
                ('whatsapp_number', models.CharField(help_text='Número con código de país, ej: 521234567890', max_length=20)),
                ('instagram_url', models.URLField(blank=True)),
                ('location', models.TextField(blank=True, verbose_name='Dirección / ubicación')),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Información de la tienda',
                'verbose_name_plural': 'Información de la tienda',
            },
        ),
    ]
