# Generated by Django 5.2.14 on 2026-05-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeinfo',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='storeinfo',
            name='tiktok_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='storeinfo',
            name='whatsapp_number',
            field=models.CharField(help_text='Número con código de país, ej: 595981123456', max_length=20),
        ),
    ]
