# Generated by Django 5.2.14 on 2026-05-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_storeinfo_facebook_url_storeinfo_tiktok_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeinfo',
            name='location',
            field=models.TextField(blank=True, verbose_name='Dirección'),
        ),
    ]
