# Generated by Django 5.2.14 on 2026-05-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_collection_banner_text_collection_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='mobile_image',
            field=models.ImageField(blank=True, null=True, upload_to='collections/mobile/', verbose_name='Imagen móvil'),
        ),
    ]
